spring:
  kafka.properties.spring.json.use.type.headers: false
  application:
    name: kafka-telemetry-data-aggregator
  cloud:
    function:
      definition: aggregateTelemetryData;consumeNasaAggregates;consumeEsaAggregates
    stream:
      bindings:
        aggregateTelemetryData-in-0:
          destination: space-probe-telemetry-data
        aggregateTelemetryData-out-0:
          destination: space-probe-aggregate-telemetry-data-nasa
        aggregateTelemetryData-out-1:
          destination: space-probe-aggregate-telemetry-data-esa
        consumeNasaAggregates-in-0:
          destination: space-probe-aggregate-telemetry-data-nasa
          group: web-dashboard
        consumeEsaAggregates-in-0:
          destination: space-probe-aggregate-telemetry-data-esa
          group: web-dashboard
      kafka:
        binder:
          brokers: "localhost:29092"
        streams:
          bindings:
            aggregateTelemetryData-in-0.consumer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: com.example.kafkasamplesstreams.serdes.TelemetryDataPointSerde
              deserializationExceptionHandler: logAndContinue
            aggregateTelemetryData-out-0.producer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: com.example.kafkasamplesstreams.serdes.AggregateTelemetryDataSerde
            aggregateTelemetryData-out-1.producer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: com.example.kafkasamplesstreams.serdes.AggregateTelemetryDataSerde
            consumeNasaAggregates-in-0.consumer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: com.example.kafkasamplesstreams.serdes.AggregateTelemetryDataSerde
            consumeEsaAggregates-in-0.consumer:
              keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              valueSerde: com.example.kafkasamplesstreams.serdes.AggregateTelemetryDataSerde
management:
  endpoints:
    web:
      exposure:
        include: "*"